version: '3.8'

services:
    mongo:
      image: mongo
      container_name: mongodb
      command: mongod --auth
      ports:
        - 27017:27017
      restart: always
      volumes:
        - /Users/wendigo/dev/mongo/data:/data/db
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

      environment:
        MONGO_INITDB_DATABASE: application_database
        MONGO_INITDB_ROOT_USERNAME: mongoadmin
        MONGO_INITDB_ROOT_PASSWORD: mongoadmin